/**
 * Supabase Database Types
 *
 * This file is auto-generated by `npm run supabase:gen-types`.
 * Do not edit manually.
 *
 * To regenerate after schema changes:
 *   npm run supabase:gen-types
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          github_id: number;
          github_username: string;
          avatar_url: string | null;
          email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          github_id: number;
          github_username: string;
          avatar_url?: string | null;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          github_id?: number;
          github_username?: string;
          avatar_url?: string | null;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      repos: {
        Row: {
          id: string;
          github_id: number;
          owner: string;
          name: string;
          full_name: string;
          is_private: boolean;
          default_branch: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          github_id: number;
          owner: string;
          name: string;
          full_name: string;
          is_private?: boolean;
          default_branch?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          github_id?: number;
          owner?: string;
          name?: string;
          full_name?: string;
          is_private?: boolean;
          default_branch?: string;
          created_at?: string;
        };
      };
      user_repos: {
        Row: {
          id: string;
          user_id: string;
          repo_id: string;
          connected_at: string;
          disconnected_at: string | null;
          settings_json: Json;
        };
        Insert: {
          id?: string;
          user_id: string;
          repo_id: string;
          connected_at?: string;
          disconnected_at?: string | null;
          settings_json?: Json;
        };
        Update: {
          id?: string;
          user_id?: string;
          repo_id?: string;
          connected_at?: string;
          disconnected_at?: string | null;
          settings_json?: Json;
        };
      };
      analysis_jobs: {
        Row: {
          id: string;
          user_id: string;
          repo_id: string;
          status: string;
          commit_count: number | null;
          analyzer_version: string;
          error_message: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          repo_id: string;
          status?: string;
          commit_count?: number | null;
          analyzer_version: string;
          error_message?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          repo_id?: string;
          status?: string;
          commit_count?: number | null;
          analyzer_version?: string;
          error_message?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
      };
      analysis_metrics: {
        Row: {
          id: string;
          job_id: string;
          metrics_json: Json;
          events_json: Json;
          computed_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          metrics_json: Json;
          events_json: Json;
          computed_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          metrics_json?: Json;
          events_json?: Json;
          computed_at?: string;
        };
      };
      analysis_reports: {
        Row: {
          id: string;
          job_id: string;
          bolokono_type: string | null;
          narrative_json: Json;
          evidence_json: Json;
          llm_model: string;
          generated_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          bolokono_type?: string | null;
          narrative_json: Json;
          evidence_json: Json;
          llm_model: string;
          generated_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          bolokono_type?: string | null;
          narrative_json?: Json;
          evidence_json?: Json;
          llm_model?: string;
          generated_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}
